# Generated by Django 5.1.2 on 2024-10-10 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcessCode",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("staff", "Staff"),
                            ("store_manager", "Store Manager"),
                            ("supplier", "Supplier"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("store_manager", "Store Manager"),
                    ("supplier", "Supplier"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
