# Generated by Django 5.1.2 on 2024-10-14 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_userrank_rename_uuid_acesscode_id_supplier_amount_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User"},
        ),
    ]
