# Generated by Django 5.1.2 on 2024-10-16 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_customuser_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="amount",
        ),
    ]
