# Generated by Django 5.1.2 on 2024-10-16 22:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_supplier_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="amount",
        ),
    ]
