# Generated by Django 5.1.2 on 2024-10-14 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehouse",
            options={
                "ordering": ["name"],
                "verbose_name": "Warehouse",
                "verbose_name_plural": "Warehouses",
            },
        ),
        migrations.AddField(
            model_name="warehouse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="warehouse",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
