# Generated by Django 5.1.2 on 2024-10-19 23:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0002_alter_warehouse_options_warehouse_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="warehouse",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
