# Generated by Django 5.1.2 on 2024-10-14 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
        ("users", "0005_userrank_rename_uuid_acesscode_id_supplier_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.supplier",
            ),
        ),
    ]
