# Generated by Django 5.1.2 on 2024-10-14 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_product_supplier"),
        ("users", "0005_userrank_rename_uuid_acesscode_id_supplier_amount_and_more"),
        ("warehouse", "0002_alter_warehouse_options_warehouse_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Product", "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.AlterModelOptions(
            name="warehousestock",
            options={
                "verbose_name": "Warehouse Stock",
                "verbose_name_plural": "Warehouse Stocks",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(max_length=255, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Category Name"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="inventory.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Product Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Product Name"),
        ),
        migrations.AlterField(
            model_name="product",
            name="reorder_level",
            field=models.PositiveIntegerField(default=1, verbose_name="Reorder Level"),
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="users.supplier",
                verbose_name="Supplier",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Unit Price"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="product_images/", verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="inventory.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="warehousestock",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="inventory.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="warehousestock",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="Quantity"),
        ),
        migrations.AlterField(
            model_name="warehousestock",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="warehouse.warehouse",
                verbose_name="Warehouse",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="warehousestock",
            unique_together={("product", "warehouse")},
        ),
    ]
