# Generated by Django 5.1.2 on 2024-10-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_alter_category_options_alter_product_options_and_more"),
        ("warehouse", "0002_alter_warehouse_options_warehouse_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="warehousestock",
            name="warehouse",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocks",
                to="warehouse.warehouse",
                verbose_name="Warehouse",
            ),
        ),
    ]
