# Generated by Django 5.1.2 on 2024-10-19 23:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
